[package]
name    = "step-dir"
version = "0.5.0"
authors = ["Hanno Braun <hanno@braun-embedded.com>"]
edition = "2018"

description = "Renamed to Stepper"
homepage    = "https://crates.io/crates/stepper"
repository  = "https://github.com/flott-motion/stepper"
license     = "0BSD"
